$log = @()

Write-Host "Running Sens_dur_6hrs..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_dur_6hrs.txt  o=Projects/India/Output/Sens_dur_6hrs.lst  --file_name_instance=Sens_dur_6hrs --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=6 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_dur_6hrs"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_dur_8hrs..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_dur_8hrs.txt  o=Projects/India/Output/Sens_dur_8hrs.lst  --file_name_instance=Sens_dur_8hrs --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=8 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_dur_8hrs"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_6hr_no_0..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_6hr_no_0.txt  o=Projects/India/Output/Sens_6hr_no_0.lst  --file_name_instance=Sens_6hr_no_0 --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=6 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=0 --cftr_instance=0 --Sw_cooldown=0 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_6hr_no_0"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_6hr_1hr_2..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_6hr_1hr_2.txt  o=Projects/India/Output/Sens_6hr_1hr_2.lst  --file_name_instance=Sens_6hr_1hr_2 --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=1 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_6hr_1hr_2"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_6hr_2hr_2..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_6hr_2hr_2.txt  o=Projects/India/Output/Sens_6hr_2hr_2.lst  --file_name_instance=Sens_6hr_2hr_2 --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_6hr_2hr_2"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_6hr_3hr_2..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_6hr_3hr_2.txt  o=Projects/India/Output/Sens_6hr_3hr_2.lst  --file_name_instance=Sens_6hr_3hr_2 --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=3 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_6hr_3hr_2"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_6hr_1hr_1..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_6hr_1hr_1.txt  o=Projects/India/Output/Sens_6hr_1hr_1.lst  --file_name_instance=Sens_6hr_1hr_1 --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=1 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=1 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_6hr_1hr_1"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_6hr_2hr_1..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_6hr_2hr_1.txt  o=Projects/India/Output/Sens_6hr_2hr_1.lst  --file_name_instance=Sens_6hr_2hr_1 --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=1 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_6hr_2hr_1"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running Sens_6hr_3hr_1..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_Sens_6hr_3hr_1.txt  o=Projects/India/Output/Sens_6hr_3hr_1.lst  --file_name_instance=Sens_6hr_3hr_1 --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/Scen_4 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2023_rajasthan --energy_sale_price_inst=dah_2023_rajasthan --energy_purchase_price_rt_inst=rtm_2023_rajasthan --energy_sale_price_RT_inst=rtm_2023_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=1 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=3 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="Sens_6hr_3hr_1"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

$outDir = "Projects/India/Output/Scen_4"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
$log | Export-Csv -Path "Projects/India/Output/Scen_4/solve_times.csv" -NoTypeInformation
Write-Host "Solve times saved to Projects/India/Output/Scen_4/solve_times.csv"
