$log = @()

Write-Host "Running 2024_dah_rtm..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_2024_dah_rtm.txt  o=Projects/India/Output/2024_2025/2024_dah_rtm.lst  --file_name_instance=2024_dah_rtm --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/2024_2025 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2024_rajasthan --energy_sale_price_inst=dah_2024_rajasthan --energy_purchase_price_rt_inst=rtm_2024_rajasthan --energy_sale_price_RT_inst=rtm_2024_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35136 --op_period_instance=8784 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="2024_dah_rtm"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running 2025_dah_rtm..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_2025_dah_rtm.txt  o=Projects/India/Output/2024_2025/2025_dah_rtm.lst  --file_name_instance=2025_dah_rtm --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/2024_2025 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2025_rajasthan --energy_sale_price_inst=dah_2025_rajasthan --energy_purchase_price_rt_inst=rtm_2025_rajasthan --energy_sale_price_RT_inst=rtm_2025_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="2025_dah_rtm"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running 2024_dah_dah..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_2024_dah_dah.txt  o=Projects/India/Output/2024_2025/2024_dah_dah.lst  --file_name_instance=2024_dah_dah --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/2024_2025 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2024_rajasthan --energy_sale_price_inst=dah_2024_rajasthan --energy_purchase_price_rt_inst=dah_2024_rajasthan --energy_sale_price_RT_inst=dah_2024_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35136 --op_period_instance=8784 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="2024_dah_dah"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running 2025_dah_dah..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_2025_dah_dah.txt  o=Projects/India/Output/2024_2025/2025_dah_dah.lst  --file_name_instance=2025_dah_dah --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/2024_2025 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=dah_2025_rajasthan --energy_sale_price_inst=dah_2025_rajasthan --energy_purchase_price_rt_inst=dah_2025_rajasthan --energy_sale_price_RT_inst=dah_2025_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="2025_dah_dah"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running 2024_rtm_rtm..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_2024_rtm_rtm.txt  o=Projects/India/Output/2024_2025/2024_rtm_rtm.lst  --file_name_instance=2024_rtm_rtm --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/2024_2025 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=rtm_2024_rajasthan --energy_sale_price_inst=rtm_2024_rajasthan --energy_purchase_price_rt_inst=rtm_2024_rajasthan --energy_sale_price_RT_inst=rtm_2024_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35136 --op_period_instance=8784 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="2024_rtm_rtm"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

Write-Host "Running 2025_rtm_rtm..."
$t = Measure-Command { cmd /c "gams Storage_dispatch_v26  logOption=4 logFile=gamslog_2025_rtm_rtm.txt  o=Projects/India/Output/2024_2025/2025_rtm_rtm.lst  --file_name_instance=2025_rtm_rtm --indir=Projects/India/Data_files/TXT_files --outdir=Projects/India/Output/2024_2025 --int_length_instance=0.25 --elec_rate_instance=15-MIN --ren_prof_instance=renewable_profiles_15min_single --energy_purchase_price_inst=rtm_2025_rajasthan --energy_sale_price_inst=rtm_2025_rajasthan --energy_purchase_price_rt_inst=rtm_2025_rajasthan --energy_sale_price_RT_inst=rtm_2025_rajasthan --input_cap_instance=500 --output_cap_instance=500 --max_output_cap_inst=500 --max_input_cap_inst=500 --allow_import_instance=1 --input_efficiency_inst=0.92 --output_efficiency_inst=0.92 --Renewable_MW_instance=0 --storage_cap_instance=2 --op_length_instance=35040 --op_period_instance=8760 --renew_cap_cost_inst=0 --input_cap_cost_inst=0 --renew_FOM_cost_inst=0 --input_FOM_cost_inst=0 --Sw_cycle_limit_both=1 --Sw_daily_cycle_limit=2 --cftr_instance=0 --Sw_cooldown=1 --Sw_cooldown_numcycle=2 --Sw_cooldown_len=1" }
$log += [PSCustomObject]@{ Scenario="2025_rtm_rtm"; Minutes=[math]::Round($t.TotalMinutes,4); Seconds=[math]::Round($t.TotalSeconds,1) }
Write-Host "  -> finished in $([math]::Round($t.TotalMinutes,2)) min"

$outDir = "Projects/India/Output/Sens_3"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
$log | Export-Csv -Path "Projects/India/Output/Sen_3/solve_times.csv" -NoTypeInformation
Write-Host "Solve times saved to Projects/India/Output/Sen_3/solve_times.csv"
