"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2026_4hr --Renewable_MW_instance=0 --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2026_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2026_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium"  --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87 --storage_cap_instance=4.00

"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2030_4hr --Renewable_MW_instance=0 --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2030_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2030_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium" --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87 --storage_cap_instance=4.00
pause

"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2040_4hr --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2040_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2040_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium"  --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87--storage_cap_instance=4.00
"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2026_2hr --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2026_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2026_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium"  --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87--storage_cap_instance=2.00
"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2030_2hr --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2030_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2030_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium" --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87 --storage_cap_instance=2.00
"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2040_2hr --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2040_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2040_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium"  --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87 --storage_cap_instance=2.00
"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2026_1hr --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2026_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2026_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium"  --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87 --storage_cap_instance=1.00
"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2030_1hr --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2030_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2030_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium" --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87 --storage_cap_instance=1.00
"C:\GAMS\34\gams.exe" Storage_dispatch_v22_1 license=C:\GAMS\34\gamslice.txt --file_name_instance=p1_2040_1hr --energy_purchase_price_inst=Cambium22_MidCase_hourly_p1_2040_energy_purchase_prices --energy_sale_price_inst=Cambium22_MidCase_hourly_p1_2040_energy_sale_prices --outdir="Projects\Solar+Storage\Output\p1_cambium"  --input_cap_instance=1 --output_cap_instance=1 --max_output_cap_inst=1 --max_input_cap_inst=1 --allow_import_instance=1 --input_efficiency_inst=0.87 --output_efficiency_inst=0.87 --storage_cap_instance=1.00

 


